services:
  backend:
    image: 827276049957.dkr.ecr.ap-south-1.amazonaws.com/todo-backend:latest
    container_name: todo-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    networks:
      - todo-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: 827276049957.dkr.ecr.ap-south-1.amazonaws.com/todo-frontend:latest
    container_name: todo-frontend
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge